### ISSUE TITLE
ROM Support

### ISSUE THREAD

**Issue by SmokeMonsterPacks** [MiSTer-devel/Vector-06C_MiSTer#1]
Great work on this core! It looks like it supports .vec files that are renamed to .rom. Most ROM collections for the Vector-06C are in .vec, so you could mention this in the readme to help people build their collection.

**Comment by sorgelig** [comment]
I didn't see any collections in .vec files. Probably it comes from specific emulator.
Usual extensions for this computer are .rom, .com, c00
